### ISSUE TITLE
The demo site base on this architecture

### ISSUE THREAD

**Issue by snese** [snese/serverless-refarch-for-ga-proxy#4]
In my opinion, we should setup the demo site that base on this architecture.

We'll provide the AGA endpoint that provide to our viewer and a dedicate streaming source to deliver the content such like the  current time.

What do you think? Can you pick up this? @hhh2012aa

**Comment by hhh2012aa** [comment]
No problem! I will provide 1. AGA endpoint 2. NLB endpoint 3. Fargate endpoint 4. IVS playback URL
